### ISSUE TITLE
Include more packages than 'package' arg

### ISSUE THREAD

**Issue by JetDrag** [jaraco/setuptools_svn#1]
there are some packages in the path controled by svn:

```
--pkg
  --__init__.py
  ...
--pkg2
  --__init__.py
  ...
setup.py
```

if I set only 'pkg' to the arg of setup function like this:
  setup(...
           packages=['pkg'])

only pkg will include in the dist before install the setuptools_svn plugin.

But after install the plugin, all file including the pkg2 will package to the dist. Pls slove it

**Comment by jaraco** [comment]
I think your issue here is that files in your repo are getting included into your source distribution. That's by design - setuptools relies on the SCM manifest to determine which packages are part of the source. What packages get built/installed, however, are determined by these other parameters, like packages. Can you confirm that it's the source dist that includes pkg2 and not a binary dist or installed package?

**Comment by jaraco** [comment]
This issue really lies with setuptools more than setuptools_scm, as setuptools_scm is following the API specified by setuptools. However, for the sake of clarity, I'll continue the discussion about this particular issue here until it's possibly determined that there's an issue with setuptools that needs to be addressed.

**Comment by JetDrag** [comment]
I've tried bdist_wheel format,no more files will be added. Even though more files will be added in the sdist, but they won't be installed when install the package with pip. The only disadvantage is that increasing the sdist size.

**Comment by jaraco** [comment]
That's good news, and everything is working as expected, even though it was somewhat surprising to you. I don't see that there's anything that setuptools or setuptools_scm could do here to help meet your expectation without drastically changing the long-standing expectation that the source dist includes all 'source' files relative to setup.py. If you have a better suggestion, you're welcome to propose it in the setuptools project, but any proposal will need to address the compatibility concerns.

**Comment by jaraco** [comment]
Oh, I just noticed that this issue was filed in setuptools_svn and not setuptools_scm. Still, all the comments remain the same (as setuptools_scm is the equivalent implementation of setuptools_svn, just for Git and Mercurial).
